name: Build APK
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-policy: 3.9
      - name: Install Buildozer
        run: |
          pip install buildozer cython==0.29.33
          sudo apt-get install -y scons libncurses5-dev libncursesw5-dev libyaml-dev libssl-dev
      - name: Build with Buildozer
        run: yes | buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-calculator-apk
          path: bin/*.apk
