name: Build APK
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.33
          sudo apt-get install -y scons libncurses5-dev libncursesw5-dev libyaml-dev libssl-dev
      - name: Build APK
        run: |
          yes | buildozer init
          # إضافة المكتبات اللازمة للتمويل
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,requests,pytelebotapi/g' buildozer.spec
          sed -i 's/title = My Application/title = Calculator/g' buildozer.spec
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: calculator-apk
          path: bin/*.apk
